package com.gotakeahike.takeahike.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a Trail.
 * This class maps to the "trail" table in the database.
 * It contains information about a hiking trail, including its name, length, experience level, and associated user.
 */

@Entity
@Table(name = "trail")
@Getter @Setter
@NoArgsConstructor
public class Trail {
    /**
     * Primary key for the Trail entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "trail_id")
    private Long id;

    @Column
    private Long appId;

    @Column(name = "trail_name")
    private String trailName;

    @Column(name = "trail_length")
    private Double trailLength;

    @Column
    @Enumerated(EnumType.STRING)
    private Experience trailExperience;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * Constructor to create a new Trail instance with specific values.
     * @param trailName - Name of the trail
     * @param trailLength - Length of the trail
     * @param trailExperience - Experience level required for the trail
     * @param user - User associated with this trail
     */

    public Trail(String trailName, Double trailLength, Experience trailExperience, User user) {
        this.trailName = trailName;
        this.trailLength = trailLength;
        this.user = user;
    }
}